// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package boomegg.cn.wawa.proto;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PktOptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:boomegg.cn.wawa.proto.PktOpt)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
     * </pre>
     *
     * <code>optional string Version = 1;</code>
     */
    java.lang.String getVersion();
    /**
     * <pre>
     * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
     * </pre>
     *
     * <code>optional string Version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional string Mtkey = 2;</code>
     */
    java.lang.String getMtkey();
    /**
     * <code>optional string Mtkey = 2;</code>
     */
    com.google.protobuf.ByteString
        getMtkeyBytes();

    /**
     * <code>optional string Skey = 3;</code>
     */
    java.lang.String getSkey();
    /**
     * <code>optional string Skey = 3;</code>
     */
    com.google.protobuf.ByteString
        getSkeyBytes();

    /**
     * <code>optional uint32 Seq = 4;</code>
     */
    int getSeq();

    /**
     * <pre>
     * ms
     * </pre>
     *
     * <code>optional uint64 TimeMs = 5;</code>
     */
    long getTimeMs();

    /**
     * <code>optional string UID = 6;</code>
     */
    java.lang.String getUID();
    /**
     * <code>optional string UID = 6;</code>
     */
    com.google.protobuf.ByteString
        getUIDBytes();

    /**
     * <pre>
     * ios | android | h5
     * </pre>
     *
     * <code>optional string Device = 7;</code>
     */
    java.lang.String getDevice();
    /**
     * <pre>
     * ios | android | h5
     * </pre>
     *
     * <code>optional string Device = 7;</code>
     */
    com.google.protobuf.ByteString
        getDeviceBytes();

    /**
     * <pre>
     * googleplay | appstore | ...
     * </pre>
     *
     * <code>optional string Channel = 8;</code>
     */
    java.lang.String getChannel();
    /**
     * <pre>
     * googleplay | appstore | ...
     * </pre>
     *
     * <code>optional string Channel = 8;</code>
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>optional string Platform = 9;</code>
     */
    java.lang.String getPlatform();
    /**
     * <code>optional string Platform = 9;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <pre>
     * zh_cn | ...
     * </pre>
     *
     * <code>optional string Lang = 10;</code>
     */
    java.lang.String getLang();
    /**
     * <pre>
     * zh_cn | ...
     * </pre>
     *
     * <code>optional string Lang = 10;</code>
     */
    com.google.protobuf.ByteString
        getLangBytes();

    /**
     * <code>optional string IP = 11;</code>
     */
    java.lang.String getIP();
    /**
     * <code>optional string IP = 11;</code>
     */
    com.google.protobuf.ByteString
        getIPBytes();

    /**
     * <code>optional string Province = 12;</code>
     */
    java.lang.String getProvince();
    /**
     * <code>optional string Province = 12;</code>
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    /**
     * <code>optional string Country = 13;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>optional string Country = 13;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();
  }
  /**
   * <pre>
   *PktOpt 用于带上请求功用参数，在短链接里面比较有用，长链接里面第一个字段填上必要的数据
   *后续的数据可以不需要填那么多，不过序列号最好每个包都带上
   * </pre>
   *
   * Protobuf type {@code boomegg.cn.wawa.proto.PktOpt}
   */
  public  static final class PktOpt extends
      com.google.protobuf.GeneratedMessageLite<
          PktOpt, PktOpt.Builder> implements
      // @@protoc_insertion_point(message_implements:boomegg.cn.wawa.proto.PktOpt)
      PktOptOrBuilder {
    private PktOpt() {
      version_ = "";
      mtkey_ = "";
      skey_ = "";
      uID_ = "";
      device_ = "";
      channel_ = "";
      platform_ = "";
      lang_ = "";
      iP_ = "";
      province_ = "";
      country_ = "";
    }
    public static final int VERSION_FIELD_NUMBER = 1;
    private java.lang.String version_;
    /**
     * <pre>
     * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
     * </pre>
     *
     * <code>optional string Version = 1;</code>
     */
    public java.lang.String getVersion() {
      return version_;
    }
    /**
     * <pre>
     * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
     * </pre>
     *
     * <code>optional string Version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(version_);
    }
    /**
     * <pre>
     * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
     * </pre>
     *
     * <code>optional string Version = 1;</code>
     */
    private void setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
    }
    /**
     * <pre>
     * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
     * </pre>
     *
     * <code>optional string Version = 1;</code>
     */
    private void clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
    }
    /**
     * <pre>
     * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
     * </pre>
     *
     * <code>optional string Version = 1;</code>
     */
    private void setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value.toStringUtf8();
    }

    public static final int MTKEY_FIELD_NUMBER = 2;
    private java.lang.String mtkey_;
    /**
     * <code>optional string Mtkey = 2;</code>
     */
    public java.lang.String getMtkey() {
      return mtkey_;
    }
    /**
     * <code>optional string Mtkey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMtkeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mtkey_);
    }
    /**
     * <code>optional string Mtkey = 2;</code>
     */
    private void setMtkey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mtkey_ = value;
    }
    /**
     * <code>optional string Mtkey = 2;</code>
     */
    private void clearMtkey() {
      
      mtkey_ = getDefaultInstance().getMtkey();
    }
    /**
     * <code>optional string Mtkey = 2;</code>
     */
    private void setMtkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mtkey_ = value.toStringUtf8();
    }

    public static final int SKEY_FIELD_NUMBER = 3;
    private java.lang.String skey_;
    /**
     * <code>optional string Skey = 3;</code>
     */
    public java.lang.String getSkey() {
      return skey_;
    }
    /**
     * <code>optional string Skey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSkeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(skey_);
    }
    /**
     * <code>optional string Skey = 3;</code>
     */
    private void setSkey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skey_ = value;
    }
    /**
     * <code>optional string Skey = 3;</code>
     */
    private void clearSkey() {
      
      skey_ = getDefaultInstance().getSkey();
    }
    /**
     * <code>optional string Skey = 3;</code>
     */
    private void setSkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skey_ = value.toStringUtf8();
    }

    public static final int SEQ_FIELD_NUMBER = 4;
    private int seq_;
    /**
     * <code>optional uint32 Seq = 4;</code>
     */
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>optional uint32 Seq = 4;</code>
     */
    private void setSeq(int value) {
      
      seq_ = value;
    }
    /**
     * <code>optional uint32 Seq = 4;</code>
     */
    private void clearSeq() {
      
      seq_ = 0;
    }

    public static final int TIMEMS_FIELD_NUMBER = 5;
    private long timeMs_;
    /**
     * <pre>
     * ms
     * </pre>
     *
     * <code>optional uint64 TimeMs = 5;</code>
     */
    public long getTimeMs() {
      return timeMs_;
    }
    /**
     * <pre>
     * ms
     * </pre>
     *
     * <code>optional uint64 TimeMs = 5;</code>
     */
    private void setTimeMs(long value) {
      
      timeMs_ = value;
    }
    /**
     * <pre>
     * ms
     * </pre>
     *
     * <code>optional uint64 TimeMs = 5;</code>
     */
    private void clearTimeMs() {
      
      timeMs_ = 0L;
    }

    public static final int UID_FIELD_NUMBER = 6;
    private java.lang.String uID_;
    /**
     * <code>optional string UID = 6;</code>
     */
    public java.lang.String getUID() {
      return uID_;
    }
    /**
     * <code>optional string UID = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUIDBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(uID_);
    }
    /**
     * <code>optional string UID = 6;</code>
     */
    private void setUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uID_ = value;
    }
    /**
     * <code>optional string UID = 6;</code>
     */
    private void clearUID() {
      
      uID_ = getDefaultInstance().getUID();
    }
    /**
     * <code>optional string UID = 6;</code>
     */
    private void setUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uID_ = value.toStringUtf8();
    }

    public static final int DEVICE_FIELD_NUMBER = 7;
    private java.lang.String device_;
    /**
     * <pre>
     * ios | android | h5
     * </pre>
     *
     * <code>optional string Device = 7;</code>
     */
    public java.lang.String getDevice() {
      return device_;
    }
    /**
     * <pre>
     * ios | android | h5
     * </pre>
     *
     * <code>optional string Device = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(device_);
    }
    /**
     * <pre>
     * ios | android | h5
     * </pre>
     *
     * <code>optional string Device = 7;</code>
     */
    private void setDevice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      device_ = value;
    }
    /**
     * <pre>
     * ios | android | h5
     * </pre>
     *
     * <code>optional string Device = 7;</code>
     */
    private void clearDevice() {
      
      device_ = getDefaultInstance().getDevice();
    }
    /**
     * <pre>
     * ios | android | h5
     * </pre>
     *
     * <code>optional string Device = 7;</code>
     */
    private void setDeviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      device_ = value.toStringUtf8();
    }

    public static final int CHANNEL_FIELD_NUMBER = 8;
    private java.lang.String channel_;
    /**
     * <pre>
     * googleplay | appstore | ...
     * </pre>
     *
     * <code>optional string Channel = 8;</code>
     */
    public java.lang.String getChannel() {
      return channel_;
    }
    /**
     * <pre>
     * googleplay | appstore | ...
     * </pre>
     *
     * <code>optional string Channel = 8;</code>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(channel_);
    }
    /**
     * <pre>
     * googleplay | appstore | ...
     * </pre>
     *
     * <code>optional string Channel = 8;</code>
     */
    private void setChannel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      channel_ = value;
    }
    /**
     * <pre>
     * googleplay | appstore | ...
     * </pre>
     *
     * <code>optional string Channel = 8;</code>
     */
    private void clearChannel() {
      
      channel_ = getDefaultInstance().getChannel();
    }
    /**
     * <pre>
     * googleplay | appstore | ...
     * </pre>
     *
     * <code>optional string Channel = 8;</code>
     */
    private void setChannelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      channel_ = value.toStringUtf8();
    }

    public static final int PLATFORM_FIELD_NUMBER = 9;
    private java.lang.String platform_;
    /**
     * <code>optional string Platform = 9;</code>
     */
    public java.lang.String getPlatform() {
      return platform_;
    }
    /**
     * <code>optional string Platform = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(platform_);
    }
    /**
     * <code>optional string Platform = 9;</code>
     */
    private void setPlatform(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platform_ = value;
    }
    /**
     * <code>optional string Platform = 9;</code>
     */
    private void clearPlatform() {
      
      platform_ = getDefaultInstance().getPlatform();
    }
    /**
     * <code>optional string Platform = 9;</code>
     */
    private void setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platform_ = value.toStringUtf8();
    }

    public static final int LANG_FIELD_NUMBER = 10;
    private java.lang.String lang_;
    /**
     * <pre>
     * zh_cn | ...
     * </pre>
     *
     * <code>optional string Lang = 10;</code>
     */
    public java.lang.String getLang() {
      return lang_;
    }
    /**
     * <pre>
     * zh_cn | ...
     * </pre>
     *
     * <code>optional string Lang = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lang_);
    }
    /**
     * <pre>
     * zh_cn | ...
     * </pre>
     *
     * <code>optional string Lang = 10;</code>
     */
    private void setLang(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lang_ = value;
    }
    /**
     * <pre>
     * zh_cn | ...
     * </pre>
     *
     * <code>optional string Lang = 10;</code>
     */
    private void clearLang() {
      
      lang_ = getDefaultInstance().getLang();
    }
    /**
     * <pre>
     * zh_cn | ...
     * </pre>
     *
     * <code>optional string Lang = 10;</code>
     */
    private void setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lang_ = value.toStringUtf8();
    }

    public static final int IP_FIELD_NUMBER = 11;
    private java.lang.String iP_;
    /**
     * <code>optional string IP = 11;</code>
     */
    public java.lang.String getIP() {
      return iP_;
    }
    /**
     * <code>optional string IP = 11;</code>
     */
    public com.google.protobuf.ByteString
        getIPBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(iP_);
    }
    /**
     * <code>optional string IP = 11;</code>
     */
    private void setIP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iP_ = value;
    }
    /**
     * <code>optional string IP = 11;</code>
     */
    private void clearIP() {
      
      iP_ = getDefaultInstance().getIP();
    }
    /**
     * <code>optional string IP = 11;</code>
     */
    private void setIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iP_ = value.toStringUtf8();
    }

    public static final int PROVINCE_FIELD_NUMBER = 12;
    private java.lang.String province_;
    /**
     * <code>optional string Province = 12;</code>
     */
    public java.lang.String getProvince() {
      return province_;
    }
    /**
     * <code>optional string Province = 12;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(province_);
    }
    /**
     * <code>optional string Province = 12;</code>
     */
    private void setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
    }
    /**
     * <code>optional string Province = 12;</code>
     */
    private void clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
    }
    /**
     * <code>optional string Province = 12;</code>
     */
    private void setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value.toStringUtf8();
    }

    public static final int COUNTRY_FIELD_NUMBER = 13;
    private java.lang.String country_;
    /**
     * <code>optional string Country = 13;</code>
     */
    public java.lang.String getCountry() {
      return country_;
    }
    /**
     * <code>optional string Country = 13;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(country_);
    }
    /**
     * <code>optional string Country = 13;</code>
     */
    private void setCountry(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
    }
    /**
     * <code>optional string Country = 13;</code>
     */
    private void clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
    }
    /**
     * <code>optional string Country = 13;</code>
     */
    private void setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!version_.isEmpty()) {
        output.writeString(1, getVersion());
      }
      if (!mtkey_.isEmpty()) {
        output.writeString(2, getMtkey());
      }
      if (!skey_.isEmpty()) {
        output.writeString(3, getSkey());
      }
      if (seq_ != 0) {
        output.writeUInt32(4, seq_);
      }
      if (timeMs_ != 0L) {
        output.writeUInt64(5, timeMs_);
      }
      if (!uID_.isEmpty()) {
        output.writeString(6, getUID());
      }
      if (!device_.isEmpty()) {
        output.writeString(7, getDevice());
      }
      if (!channel_.isEmpty()) {
        output.writeString(8, getChannel());
      }
      if (!platform_.isEmpty()) {
        output.writeString(9, getPlatform());
      }
      if (!lang_.isEmpty()) {
        output.writeString(10, getLang());
      }
      if (!iP_.isEmpty()) {
        output.writeString(11, getIP());
      }
      if (!province_.isEmpty()) {
        output.writeString(12, getProvince());
      }
      if (!country_.isEmpty()) {
        output.writeString(13, getCountry());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!version_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getVersion());
      }
      if (!mtkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMtkey());
      }
      if (!skey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSkey());
      }
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, seq_);
      }
      if (timeMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, timeMs_);
      }
      if (!uID_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getUID());
      }
      if (!device_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getDevice());
      }
      if (!channel_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getChannel());
      }
      if (!platform_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getPlatform());
      }
      if (!lang_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getLang());
      }
      if (!iP_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getIP());
      }
      if (!province_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getProvince());
      }
      if (!country_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getCountry());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktOpt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(boomegg.cn.wawa.proto.Base.PktOpt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *PktOpt 用于带上请求功用参数，在短链接里面比较有用，长链接里面第一个字段填上必要的数据
     *后续的数据可以不需要填那么多，不过序列号最好每个包都带上
     * </pre>
     *
     * Protobuf type {@code boomegg.cn.wawa.proto.PktOpt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          boomegg.cn.wawa.proto.Base.PktOpt, Builder> implements
        // @@protoc_insertion_point(builder_implements:boomegg.cn.wawa.proto.PktOpt)
        boomegg.cn.wawa.proto.Base.PktOptOrBuilder {
      // Construct using boomegg.cn.wawa.proto.Base.PktOpt.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
       * </pre>
       *
       * <code>optional string Version = 1;</code>
       */
      public java.lang.String getVersion() {
        return instance.getVersion();
      }
      /**
       * <pre>
       * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
       * </pre>
       *
       * <code>optional string Version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        return instance.getVersionBytes();
      }
      /**
       * <pre>
       * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
       * </pre>
       *
       * <code>optional string Version = 1;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <pre>
       * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
       * </pre>
       *
       * <code>optional string Version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }
      /**
       * <pre>
       * 1.0.1.142 前三个为应用版本号，最后一个为热更新版本号，每个版本号占一个字节
       * </pre>
       *
       * <code>optional string Version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVersionBytes(value);
        return this;
      }

      /**
       * <code>optional string Mtkey = 2;</code>
       */
      public java.lang.String getMtkey() {
        return instance.getMtkey();
      }
      /**
       * <code>optional string Mtkey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMtkeyBytes() {
        return instance.getMtkeyBytes();
      }
      /**
       * <code>optional string Mtkey = 2;</code>
       */
      public Builder setMtkey(
          java.lang.String value) {
        copyOnWrite();
        instance.setMtkey(value);
        return this;
      }
      /**
       * <code>optional string Mtkey = 2;</code>
       */
      public Builder clearMtkey() {
        copyOnWrite();
        instance.clearMtkey();
        return this;
      }
      /**
       * <code>optional string Mtkey = 2;</code>
       */
      public Builder setMtkeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMtkeyBytes(value);
        return this;
      }

      /**
       * <code>optional string Skey = 3;</code>
       */
      public java.lang.String getSkey() {
        return instance.getSkey();
      }
      /**
       * <code>optional string Skey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSkeyBytes() {
        return instance.getSkeyBytes();
      }
      /**
       * <code>optional string Skey = 3;</code>
       */
      public Builder setSkey(
          java.lang.String value) {
        copyOnWrite();
        instance.setSkey(value);
        return this;
      }
      /**
       * <code>optional string Skey = 3;</code>
       */
      public Builder clearSkey() {
        copyOnWrite();
        instance.clearSkey();
        return this;
      }
      /**
       * <code>optional string Skey = 3;</code>
       */
      public Builder setSkeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSkeyBytes(value);
        return this;
      }

      /**
       * <code>optional uint32 Seq = 4;</code>
       */
      public int getSeq() {
        return instance.getSeq();
      }
      /**
       * <code>optional uint32 Seq = 4;</code>
       */
      public Builder setSeq(int value) {
        copyOnWrite();
        instance.setSeq(value);
        return this;
      }
      /**
       * <code>optional uint32 Seq = 4;</code>
       */
      public Builder clearSeq() {
        copyOnWrite();
        instance.clearSeq();
        return this;
      }

      /**
       * <pre>
       * ms
       * </pre>
       *
       * <code>optional uint64 TimeMs = 5;</code>
       */
      public long getTimeMs() {
        return instance.getTimeMs();
      }
      /**
       * <pre>
       * ms
       * </pre>
       *
       * <code>optional uint64 TimeMs = 5;</code>
       */
      public Builder setTimeMs(long value) {
        copyOnWrite();
        instance.setTimeMs(value);
        return this;
      }
      /**
       * <pre>
       * ms
       * </pre>
       *
       * <code>optional uint64 TimeMs = 5;</code>
       */
      public Builder clearTimeMs() {
        copyOnWrite();
        instance.clearTimeMs();
        return this;
      }

      /**
       * <code>optional string UID = 6;</code>
       */
      public java.lang.String getUID() {
        return instance.getUID();
      }
      /**
       * <code>optional string UID = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUIDBytes() {
        return instance.getUIDBytes();
      }
      /**
       * <code>optional string UID = 6;</code>
       */
      public Builder setUID(
          java.lang.String value) {
        copyOnWrite();
        instance.setUID(value);
        return this;
      }
      /**
       * <code>optional string UID = 6;</code>
       */
      public Builder clearUID() {
        copyOnWrite();
        instance.clearUID();
        return this;
      }
      /**
       * <code>optional string UID = 6;</code>
       */
      public Builder setUIDBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUIDBytes(value);
        return this;
      }

      /**
       * <pre>
       * ios | android | h5
       * </pre>
       *
       * <code>optional string Device = 7;</code>
       */
      public java.lang.String getDevice() {
        return instance.getDevice();
      }
      /**
       * <pre>
       * ios | android | h5
       * </pre>
       *
       * <code>optional string Device = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceBytes() {
        return instance.getDeviceBytes();
      }
      /**
       * <pre>
       * ios | android | h5
       * </pre>
       *
       * <code>optional string Device = 7;</code>
       */
      public Builder setDevice(
          java.lang.String value) {
        copyOnWrite();
        instance.setDevice(value);
        return this;
      }
      /**
       * <pre>
       * ios | android | h5
       * </pre>
       *
       * <code>optional string Device = 7;</code>
       */
      public Builder clearDevice() {
        copyOnWrite();
        instance.clearDevice();
        return this;
      }
      /**
       * <pre>
       * ios | android | h5
       * </pre>
       *
       * <code>optional string Device = 7;</code>
       */
      public Builder setDeviceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceBytes(value);
        return this;
      }

      /**
       * <pre>
       * googleplay | appstore | ...
       * </pre>
       *
       * <code>optional string Channel = 8;</code>
       */
      public java.lang.String getChannel() {
        return instance.getChannel();
      }
      /**
       * <pre>
       * googleplay | appstore | ...
       * </pre>
       *
       * <code>optional string Channel = 8;</code>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        return instance.getChannelBytes();
      }
      /**
       * <pre>
       * googleplay | appstore | ...
       * </pre>
       *
       * <code>optional string Channel = 8;</code>
       */
      public Builder setChannel(
          java.lang.String value) {
        copyOnWrite();
        instance.setChannel(value);
        return this;
      }
      /**
       * <pre>
       * googleplay | appstore | ...
       * </pre>
       *
       * <code>optional string Channel = 8;</code>
       */
      public Builder clearChannel() {
        copyOnWrite();
        instance.clearChannel();
        return this;
      }
      /**
       * <pre>
       * googleplay | appstore | ...
       * </pre>
       *
       * <code>optional string Channel = 8;</code>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChannelBytes(value);
        return this;
      }

      /**
       * <code>optional string Platform = 9;</code>
       */
      public java.lang.String getPlatform() {
        return instance.getPlatform();
      }
      /**
       * <code>optional string Platform = 9;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        return instance.getPlatformBytes();
      }
      /**
       * <code>optional string Platform = 9;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        copyOnWrite();
        instance.setPlatform(value);
        return this;
      }
      /**
       * <code>optional string Platform = 9;</code>
       */
      public Builder clearPlatform() {
        copyOnWrite();
        instance.clearPlatform();
        return this;
      }
      /**
       * <code>optional string Platform = 9;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPlatformBytes(value);
        return this;
      }

      /**
       * <pre>
       * zh_cn | ...
       * </pre>
       *
       * <code>optional string Lang = 10;</code>
       */
      public java.lang.String getLang() {
        return instance.getLang();
      }
      /**
       * <pre>
       * zh_cn | ...
       * </pre>
       *
       * <code>optional string Lang = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLangBytes() {
        return instance.getLangBytes();
      }
      /**
       * <pre>
       * zh_cn | ...
       * </pre>
       *
       * <code>optional string Lang = 10;</code>
       */
      public Builder setLang(
          java.lang.String value) {
        copyOnWrite();
        instance.setLang(value);
        return this;
      }
      /**
       * <pre>
       * zh_cn | ...
       * </pre>
       *
       * <code>optional string Lang = 10;</code>
       */
      public Builder clearLang() {
        copyOnWrite();
        instance.clearLang();
        return this;
      }
      /**
       * <pre>
       * zh_cn | ...
       * </pre>
       *
       * <code>optional string Lang = 10;</code>
       */
      public Builder setLangBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLangBytes(value);
        return this;
      }

      /**
       * <code>optional string IP = 11;</code>
       */
      public java.lang.String getIP() {
        return instance.getIP();
      }
      /**
       * <code>optional string IP = 11;</code>
       */
      public com.google.protobuf.ByteString
          getIPBytes() {
        return instance.getIPBytes();
      }
      /**
       * <code>optional string IP = 11;</code>
       */
      public Builder setIP(
          java.lang.String value) {
        copyOnWrite();
        instance.setIP(value);
        return this;
      }
      /**
       * <code>optional string IP = 11;</code>
       */
      public Builder clearIP() {
        copyOnWrite();
        instance.clearIP();
        return this;
      }
      /**
       * <code>optional string IP = 11;</code>
       */
      public Builder setIPBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIPBytes(value);
        return this;
      }

      /**
       * <code>optional string Province = 12;</code>
       */
      public java.lang.String getProvince() {
        return instance.getProvince();
      }
      /**
       * <code>optional string Province = 12;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        return instance.getProvinceBytes();
      }
      /**
       * <code>optional string Province = 12;</code>
       */
      public Builder setProvince(
          java.lang.String value) {
        copyOnWrite();
        instance.setProvince(value);
        return this;
      }
      /**
       * <code>optional string Province = 12;</code>
       */
      public Builder clearProvince() {
        copyOnWrite();
        instance.clearProvince();
        return this;
      }
      /**
       * <code>optional string Province = 12;</code>
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProvinceBytes(value);
        return this;
      }

      /**
       * <code>optional string Country = 13;</code>
       */
      public java.lang.String getCountry() {
        return instance.getCountry();
      }
      /**
       * <code>optional string Country = 13;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        return instance.getCountryBytes();
      }
      /**
       * <code>optional string Country = 13;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        copyOnWrite();
        instance.setCountry(value);
        return this;
      }
      /**
       * <code>optional string Country = 13;</code>
       */
      public Builder clearCountry() {
        copyOnWrite();
        instance.clearCountry();
        return this;
      }
      /**
       * <code>optional string Country = 13;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCountryBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boomegg.cn.wawa.proto.PktOpt)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new boomegg.cn.wawa.proto.Base.PktOpt();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          boomegg.cn.wawa.proto.Base.PktOpt other = (boomegg.cn.wawa.proto.Base.PktOpt) arg1;
          version_ = visitor.visitString(!version_.isEmpty(), version_,
              !other.version_.isEmpty(), other.version_);
          mtkey_ = visitor.visitString(!mtkey_.isEmpty(), mtkey_,
              !other.mtkey_.isEmpty(), other.mtkey_);
          skey_ = visitor.visitString(!skey_.isEmpty(), skey_,
              !other.skey_.isEmpty(), other.skey_);
          seq_ = visitor.visitInt(seq_ != 0, seq_,
              other.seq_ != 0, other.seq_);
          timeMs_ = visitor.visitLong(timeMs_ != 0L, timeMs_,
              other.timeMs_ != 0L, other.timeMs_);
          uID_ = visitor.visitString(!uID_.isEmpty(), uID_,
              !other.uID_.isEmpty(), other.uID_);
          device_ = visitor.visitString(!device_.isEmpty(), device_,
              !other.device_.isEmpty(), other.device_);
          channel_ = visitor.visitString(!channel_.isEmpty(), channel_,
              !other.channel_.isEmpty(), other.channel_);
          platform_ = visitor.visitString(!platform_.isEmpty(), platform_,
              !other.platform_.isEmpty(), other.platform_);
          lang_ = visitor.visitString(!lang_.isEmpty(), lang_,
              !other.lang_.isEmpty(), other.lang_);
          iP_ = visitor.visitString(!iP_.isEmpty(), iP_,
              !other.iP_.isEmpty(), other.iP_);
          province_ = visitor.visitString(!province_.isEmpty(), province_,
              !other.province_.isEmpty(), other.province_);
          country_ = visitor.visitString(!country_.isEmpty(), country_,
              !other.country_.isEmpty(), other.country_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  version_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  mtkey_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  skey_ = s;
                  break;
                }
                case 32: {

                  seq_ = input.readUInt32();
                  break;
                }
                case 40: {

                  timeMs_ = input.readUInt64();
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  uID_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  device_ = s;
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  channel_ = s;
                  break;
                }
                case 74: {
                  String s = input.readStringRequireUtf8();

                  platform_ = s;
                  break;
                }
                case 82: {
                  String s = input.readStringRequireUtf8();

                  lang_ = s;
                  break;
                }
                case 90: {
                  String s = input.readStringRequireUtf8();

                  iP_ = s;
                  break;
                }
                case 98: {
                  String s = input.readStringRequireUtf8();

                  province_ = s;
                  break;
                }
                case 106: {
                  String s = input.readStringRequireUtf8();

                  country_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (boomegg.cn.wawa.proto.Base.PktOpt.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:boomegg.cn.wawa.proto.PktOpt)
    private static final boomegg.cn.wawa.proto.Base.PktOpt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PktOpt();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static boomegg.cn.wawa.proto.Base.PktOpt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PktOpt> PARSER;

    public static com.google.protobuf.Parser<PktOpt> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PktInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:boomegg.cn.wawa.proto.PktInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 Cmd = 1;</code>
     */
    int getCmd();

    /**
     * <code>optional int32 Len = 2;</code>
     */
    int getLen();
  }
  /**
   * Protobuf type {@code boomegg.cn.wawa.proto.PktInfo}
   */
  public  static final class PktInfo extends
      com.google.protobuf.GeneratedMessageLite<
          PktInfo, PktInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:boomegg.cn.wawa.proto.PktInfo)
      PktInfoOrBuilder {
    private PktInfo() {
    }
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>optional int32 Cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }
    /**
     * <code>optional int32 Cmd = 1;</code>
     */
    private void setCmd(int value) {
      
      cmd_ = value;
    }
    /**
     * <code>optional int32 Cmd = 1;</code>
     */
    private void clearCmd() {
      
      cmd_ = 0;
    }

    public static final int LEN_FIELD_NUMBER = 2;
    private int len_;
    /**
     * <code>optional int32 Len = 2;</code>
     */
    public int getLen() {
      return len_;
    }
    /**
     * <code>optional int32 Len = 2;</code>
     */
    private void setLen(int value) {
      
      len_ = value;
    }
    /**
     * <code>optional int32 Len = 2;</code>
     */
    private void clearLen() {
      
      len_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(1, cmd_);
      }
      if (len_ != 0) {
        output.writeInt32(2, len_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (len_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, len_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(boomegg.cn.wawa.proto.Base.PktInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code boomegg.cn.wawa.proto.PktInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          boomegg.cn.wawa.proto.Base.PktInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:boomegg.cn.wawa.proto.PktInfo)
        boomegg.cn.wawa.proto.Base.PktInfoOrBuilder {
      // Construct using boomegg.cn.wawa.proto.Base.PktInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 Cmd = 1;</code>
       */
      public int getCmd() {
        return instance.getCmd();
      }
      /**
       * <code>optional int32 Cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        copyOnWrite();
        instance.setCmd(value);
        return this;
      }
      /**
       * <code>optional int32 Cmd = 1;</code>
       */
      public Builder clearCmd() {
        copyOnWrite();
        instance.clearCmd();
        return this;
      }

      /**
       * <code>optional int32 Len = 2;</code>
       */
      public int getLen() {
        return instance.getLen();
      }
      /**
       * <code>optional int32 Len = 2;</code>
       */
      public Builder setLen(int value) {
        copyOnWrite();
        instance.setLen(value);
        return this;
      }
      /**
       * <code>optional int32 Len = 2;</code>
       */
      public Builder clearLen() {
        copyOnWrite();
        instance.clearLen();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boomegg.cn.wawa.proto.PktInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new boomegg.cn.wawa.proto.Base.PktInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          boomegg.cn.wawa.proto.Base.PktInfo other = (boomegg.cn.wawa.proto.Base.PktInfo) arg1;
          cmd_ = visitor.visitInt(cmd_ != 0, cmd_,
              other.cmd_ != 0, other.cmd_);
          len_ = visitor.visitInt(len_ != 0, len_,
              other.len_ != 0, other.len_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  cmd_ = input.readInt32();
                  break;
                }
                case 16: {

                  len_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (boomegg.cn.wawa.proto.Base.PktInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:boomegg.cn.wawa.proto.PktInfo)
    private static final boomegg.cn.wawa.proto.Base.PktInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PktInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static boomegg.cn.wawa.proto.Base.PktInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PktInfo> PARSER;

    public static com.google.protobuf.Parser<PktInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PktHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:boomegg.cn.wawa.proto.PktHead)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    boolean hasOpt();
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    boomegg.cn.wawa.proto.Base.PktOpt getOpt();

    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    boolean hasPktInfo();
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    boomegg.cn.wawa.proto.Base.PktInfo getPktInfo();
  }
  /**
   * Protobuf type {@code boomegg.cn.wawa.proto.PktHead}
   */
  public  static final class PktHead extends
      com.google.protobuf.GeneratedMessageLite<
          PktHead, PktHead.Builder> implements
      // @@protoc_insertion_point(message_implements:boomegg.cn.wawa.proto.PktHead)
      PktHeadOrBuilder {
    private PktHead() {
    }
    public static final int OPT_FIELD_NUMBER = 1;
    private boomegg.cn.wawa.proto.Base.PktOpt opt_;
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    public boolean hasOpt() {
      return opt_ != null;
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    public boomegg.cn.wawa.proto.Base.PktOpt getOpt() {
      return opt_ == null ? boomegg.cn.wawa.proto.Base.PktOpt.getDefaultInstance() : opt_;
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    private void setOpt(boomegg.cn.wawa.proto.Base.PktOpt value) {
      if (value == null) {
        throw new NullPointerException();
      }
      opt_ = value;
      
      }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    private void setOpt(
        boomegg.cn.wawa.proto.Base.PktOpt.Builder builderForValue) {
      opt_ = builderForValue.build();
      
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    private void mergeOpt(boomegg.cn.wawa.proto.Base.PktOpt value) {
      if (opt_ != null &&
          opt_ != boomegg.cn.wawa.proto.Base.PktOpt.getDefaultInstance()) {
        opt_ =
          boomegg.cn.wawa.proto.Base.PktOpt.newBuilder(opt_).mergeFrom(value).buildPartial();
      } else {
        opt_ = value;
      }
      
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
     */
    private void clearOpt() {  opt_ = null;
      
    }

    public static final int PKTINFO_FIELD_NUMBER = 2;
    private boomegg.cn.wawa.proto.Base.PktInfo pktInfo_;
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    public boolean hasPktInfo() {
      return pktInfo_ != null;
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    public boomegg.cn.wawa.proto.Base.PktInfo getPktInfo() {
      return pktInfo_ == null ? boomegg.cn.wawa.proto.Base.PktInfo.getDefaultInstance() : pktInfo_;
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    private void setPktInfo(boomegg.cn.wawa.proto.Base.PktInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      pktInfo_ = value;
      
      }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    private void setPktInfo(
        boomegg.cn.wawa.proto.Base.PktInfo.Builder builderForValue) {
      pktInfo_ = builderForValue.build();
      
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    private void mergePktInfo(boomegg.cn.wawa.proto.Base.PktInfo value) {
      if (pktInfo_ != null &&
          pktInfo_ != boomegg.cn.wawa.proto.Base.PktInfo.getDefaultInstance()) {
        pktInfo_ =
          boomegg.cn.wawa.proto.Base.PktInfo.newBuilder(pktInfo_).mergeFrom(value).buildPartial();
      } else {
        pktInfo_ = value;
      }
      
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
     */
    private void clearPktInfo() {  pktInfo_ = null;
      
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (opt_ != null) {
        output.writeMessage(1, getOpt());
      }
      if (pktInfo_ != null) {
        output.writeMessage(2, getPktInfo());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (opt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOpt());
      }
      if (pktInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPktInfo());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.PktHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(boomegg.cn.wawa.proto.Base.PktHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code boomegg.cn.wawa.proto.PktHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          boomegg.cn.wawa.proto.Base.PktHead, Builder> implements
        // @@protoc_insertion_point(builder_implements:boomegg.cn.wawa.proto.PktHead)
        boomegg.cn.wawa.proto.Base.PktHeadOrBuilder {
      // Construct using boomegg.cn.wawa.proto.Base.PktHead.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
       */
      public boolean hasOpt() {
        return instance.hasOpt();
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
       */
      public boomegg.cn.wawa.proto.Base.PktOpt getOpt() {
        return instance.getOpt();
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
       */
      public Builder setOpt(boomegg.cn.wawa.proto.Base.PktOpt value) {
        copyOnWrite();
        instance.setOpt(value);
        return this;
        }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
       */
      public Builder setOpt(
          boomegg.cn.wawa.proto.Base.PktOpt.Builder builderForValue) {
        copyOnWrite();
        instance.setOpt(builderForValue);
        return this;
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
       */
      public Builder mergeOpt(boomegg.cn.wawa.proto.Base.PktOpt value) {
        copyOnWrite();
        instance.mergeOpt(value);
        return this;
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktOpt Opt = 1;</code>
       */
      public Builder clearOpt() {  copyOnWrite();
        instance.clearOpt();
        return this;
      }

      /**
       * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
       */
      public boolean hasPktInfo() {
        return instance.hasPktInfo();
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
       */
      public boomegg.cn.wawa.proto.Base.PktInfo getPktInfo() {
        return instance.getPktInfo();
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
       */
      public Builder setPktInfo(boomegg.cn.wawa.proto.Base.PktInfo value) {
        copyOnWrite();
        instance.setPktInfo(value);
        return this;
        }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
       */
      public Builder setPktInfo(
          boomegg.cn.wawa.proto.Base.PktInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setPktInfo(builderForValue);
        return this;
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
       */
      public Builder mergePktInfo(boomegg.cn.wawa.proto.Base.PktInfo value) {
        copyOnWrite();
        instance.mergePktInfo(value);
        return this;
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktInfo PktInfo = 2;</code>
       */
      public Builder clearPktInfo() {  copyOnWrite();
        instance.clearPktInfo();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boomegg.cn.wawa.proto.PktHead)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new boomegg.cn.wawa.proto.Base.PktHead();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          boomegg.cn.wawa.proto.Base.PktHead other = (boomegg.cn.wawa.proto.Base.PktHead) arg1;
          opt_ = visitor.visitMessage(opt_, other.opt_);
          pktInfo_ = visitor.visitMessage(pktInfo_, other.pktInfo_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  boomegg.cn.wawa.proto.Base.PktOpt.Builder subBuilder = null;
                  if (opt_ != null) {
                    subBuilder = opt_.toBuilder();
                  }
                  opt_ = input.readMessage(boomegg.cn.wawa.proto.Base.PktOpt.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(opt_);
                    opt_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  boomegg.cn.wawa.proto.Base.PktInfo.Builder subBuilder = null;
                  if (pktInfo_ != null) {
                    subBuilder = pktInfo_.toBuilder();
                  }
                  pktInfo_ = input.readMessage(boomegg.cn.wawa.proto.Base.PktInfo.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(pktInfo_);
                    pktInfo_ = subBuilder.buildPartial();
                  }

                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (boomegg.cn.wawa.proto.Base.PktHead.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:boomegg.cn.wawa.proto.PktHead)
    private static final boomegg.cn.wawa.proto.Base.PktHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PktHead();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static boomegg.cn.wawa.proto.Base.PktHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PktHead> PARSER;

    public static com.google.protobuf.Parser<PktHead> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:boomegg.cn.wawa.proto.Packet)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    boomegg.cn.wawa.proto.Base.PktHead getHead();

    /**
     * <code>optional bytes Body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code boomegg.cn.wawa.proto.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageLite<
          Packet, Packet.Builder> implements
      // @@protoc_insertion_point(message_implements:boomegg.cn.wawa.proto.Packet)
      PacketOrBuilder {
    private Packet() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int HEAD_FIELD_NUMBER = 1;
    private boomegg.cn.wawa.proto.Base.PktHead head_;
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    public boolean hasHead() {
      return head_ != null;
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    public boomegg.cn.wawa.proto.Base.PktHead getHead() {
      return head_ == null ? boomegg.cn.wawa.proto.Base.PktHead.getDefaultInstance() : head_;
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    private void setHead(boomegg.cn.wawa.proto.Base.PktHead value) {
      if (value == null) {
        throw new NullPointerException();
      }
      head_ = value;
      
      }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    private void setHead(
        boomegg.cn.wawa.proto.Base.PktHead.Builder builderForValue) {
      head_ = builderForValue.build();
      
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    private void mergeHead(boomegg.cn.wawa.proto.Base.PktHead value) {
      if (head_ != null &&
          head_ != boomegg.cn.wawa.proto.Base.PktHead.getDefaultInstance()) {
        head_ =
          boomegg.cn.wawa.proto.Base.PktHead.newBuilder(head_).mergeFrom(value).buildPartial();
      } else {
        head_ = value;
      }
      
    }
    /**
     * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
     */
    private void clearHead() {  head_ = null;
      
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes Body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>optional bytes Body = 2;</code>
     */
    private void setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
    }
    /**
     * <code>optional bytes Body = 2;</code>
     */
    private void clearBody() {
      
      body_ = getDefaultInstance().getBody();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (head_ != null) {
        output.writeMessage(1, getHead());
      }
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (head_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHead());
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(boomegg.cn.wawa.proto.Base.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code boomegg.cn.wawa.proto.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          boomegg.cn.wawa.proto.Base.Packet, Builder> implements
        // @@protoc_insertion_point(builder_implements:boomegg.cn.wawa.proto.Packet)
        boomegg.cn.wawa.proto.Base.PacketOrBuilder {
      // Construct using boomegg.cn.wawa.proto.Base.Packet.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
       */
      public boolean hasHead() {
        return instance.hasHead();
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
       */
      public boomegg.cn.wawa.proto.Base.PktHead getHead() {
        return instance.getHead();
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
       */
      public Builder setHead(boomegg.cn.wawa.proto.Base.PktHead value) {
        copyOnWrite();
        instance.setHead(value);
        return this;
        }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
       */
      public Builder setHead(
          boomegg.cn.wawa.proto.Base.PktHead.Builder builderForValue) {
        copyOnWrite();
        instance.setHead(builderForValue);
        return this;
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
       */
      public Builder mergeHead(boomegg.cn.wawa.proto.Base.PktHead value) {
        copyOnWrite();
        instance.mergeHead(value);
        return this;
      }
      /**
       * <code>optional .boomegg.cn.wawa.proto.PktHead Head = 1;</code>
       */
      public Builder clearHead() {  copyOnWrite();
        instance.clearHead();
        return this;
      }

      /**
       * <code>optional bytes Body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return instance.getBody();
      }
      /**
       * <code>optional bytes Body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBody(value);
        return this;
      }
      /**
       * <code>optional bytes Body = 2;</code>
       */
      public Builder clearBody() {
        copyOnWrite();
        instance.clearBody();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boomegg.cn.wawa.proto.Packet)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new boomegg.cn.wawa.proto.Base.Packet();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          boomegg.cn.wawa.proto.Base.Packet other = (boomegg.cn.wawa.proto.Base.Packet) arg1;
          head_ = visitor.visitMessage(head_, other.head_);
          body_ = visitor.visitByteString(body_ != com.google.protobuf.ByteString.EMPTY, body_,
              other.body_ != com.google.protobuf.ByteString.EMPTY, other.body_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  boomegg.cn.wawa.proto.Base.PktHead.Builder subBuilder = null;
                  if (head_ != null) {
                    subBuilder = head_.toBuilder();
                  }
                  head_ = input.readMessage(boomegg.cn.wawa.proto.Base.PktHead.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(head_);
                    head_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {

                  body_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (boomegg.cn.wawa.proto.Base.Packet.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:boomegg.cn.wawa.proto.Packet)
    private static final boomegg.cn.wawa.proto.Base.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Packet();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static boomegg.cn.wawa.proto.Base.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Packet> PARSER;

    public static com.google.protobuf.Parser<Packet> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RspHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:boomegg.cn.wawa.proto.RspHead)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 RetCode = 1;</code>
     */
    int getRetCode();

    /**
     * <code>optional string RetMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string RetMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();
  }
  /**
   * Protobuf type {@code boomegg.cn.wawa.proto.RspHead}
   */
  public  static final class RspHead extends
      com.google.protobuf.GeneratedMessageLite<
          RspHead, RspHead.Builder> implements
      // @@protoc_insertion_point(message_implements:boomegg.cn.wawa.proto.RspHead)
      RspHeadOrBuilder {
    private RspHead() {
      retMsg_ = "";
    }
    public static final int RETCODE_FIELD_NUMBER = 1;
    private int retCode_;
    /**
     * <code>optional int32 RetCode = 1;</code>
     */
    public int getRetCode() {
      return retCode_;
    }
    /**
     * <code>optional int32 RetCode = 1;</code>
     */
    private void setRetCode(int value) {
      
      retCode_ = value;
    }
    /**
     * <code>optional int32 RetCode = 1;</code>
     */
    private void clearRetCode() {
      
      retCode_ = 0;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private java.lang.String retMsg_;
    /**
     * <code>optional string RetMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      return retMsg_;
    }
    /**
     * <code>optional string RetMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(retMsg_);
    }
    /**
     * <code>optional string RetMsg = 2;</code>
     */
    private void setRetMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      retMsg_ = value;
    }
    /**
     * <code>optional string RetMsg = 2;</code>
     */
    private void clearRetMsg() {
      
      retMsg_ = getDefaultInstance().getRetMsg();
    }
    /**
     * <code>optional string RetMsg = 2;</code>
     */
    private void setRetMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      retMsg_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (retCode_ != 0) {
        output.writeInt32(1, retCode_);
      }
      if (!retMsg_.isEmpty()) {
        output.writeString(2, getRetMsg());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (retCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retCode_);
      }
      if (!retMsg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getRetMsg());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static boomegg.cn.wawa.proto.Base.RspHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(boomegg.cn.wawa.proto.Base.RspHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code boomegg.cn.wawa.proto.RspHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          boomegg.cn.wawa.proto.Base.RspHead, Builder> implements
        // @@protoc_insertion_point(builder_implements:boomegg.cn.wawa.proto.RspHead)
        boomegg.cn.wawa.proto.Base.RspHeadOrBuilder {
      // Construct using boomegg.cn.wawa.proto.Base.RspHead.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 RetCode = 1;</code>
       */
      public int getRetCode() {
        return instance.getRetCode();
      }
      /**
       * <code>optional int32 RetCode = 1;</code>
       */
      public Builder setRetCode(int value) {
        copyOnWrite();
        instance.setRetCode(value);
        return this;
      }
      /**
       * <code>optional int32 RetCode = 1;</code>
       */
      public Builder clearRetCode() {
        copyOnWrite();
        instance.clearRetCode();
        return this;
      }

      /**
       * <code>optional string RetMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        return instance.getRetMsg();
      }
      /**
       * <code>optional string RetMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        return instance.getRetMsgBytes();
      }
      /**
       * <code>optional string RetMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setRetMsg(value);
        return this;
      }
      /**
       * <code>optional string RetMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        copyOnWrite();
        instance.clearRetMsg();
        return this;
      }
      /**
       * <code>optional string RetMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRetMsgBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boomegg.cn.wawa.proto.RspHead)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new boomegg.cn.wawa.proto.Base.RspHead();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          boomegg.cn.wawa.proto.Base.RspHead other = (boomegg.cn.wawa.proto.Base.RspHead) arg1;
          retCode_ = visitor.visitInt(retCode_ != 0, retCode_,
              other.retCode_ != 0, other.retCode_);
          retMsg_ = visitor.visitString(!retMsg_.isEmpty(), retMsg_,
              !other.retMsg_.isEmpty(), other.retMsg_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  retCode_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  retMsg_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (boomegg.cn.wawa.proto.Base.RspHead.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:boomegg.cn.wawa.proto.RspHead)
    private static final boomegg.cn.wawa.proto.Base.RspHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RspHead();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static boomegg.cn.wawa.proto.Base.RspHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RspHead> PARSER;

    public static com.google.protobuf.Parser<RspHead> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
