// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package boomegg.cn.wawa.proto;

public final class Cmd {
  private Cmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code boomegg.cn.wawa.proto.GAME_CMD}
   */
  public enum GAME_CMD
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>GAME_CMD_INIT = 0;</code>
     */
    GAME_CMD_INIT(0),
    /**
     * <pre>
     *以下是娃娃机自动向srv上报的请求
     *娃娃机初始化登录命令字,娃娃机向srv注册自己
     * </pre>
     *
     * <code>GAME_CMD_WAWA_REG_REQ = 100001;</code>
     */
    GAME_CMD_WAWA_REG_REQ(100001),
    /**
     * <code>GAME_CMD_WAWA_REG_RESP = 100002;</code>
     */
    GAME_CMD_WAWA_REG_RESP(100002),
    /**
     * <pre>
     *娃娃机抓取结果
     * </pre>
     *
     * <code>GAME_CMD_WAWA_NOTIFY_REQ = 100003;</code>
     */
    GAME_CMD_WAWA_NOTIFY_REQ(100003),
    /**
     * <code>GAME_CMD_WAWA_NOTIFY_RESP = 100004;</code>
     */
    GAME_CMD_WAWA_NOTIFY_RESP(100004),
    /**
     * <pre>
     *娃娃机心跳协议
     * </pre>
     *
     * <code>GAME_CMD_WAWA_HB_REQ = 100005;</code>
     */
    GAME_CMD_WAWA_HB_REQ(100005),
    /**
     * <code>GAME_CMD_WAWA_HB_RESP = 100006;</code>
     */
    GAME_CMD_WAWA_HB_RESP(100006),
    /**
     * <pre>
     *娃娃机向srv更新信息(cover)
     * </pre>
     *
     * <code>GAME_CMD_UPDATE_ROOM_INFO_REQ = 100007;</code>
     */
    GAME_CMD_UPDATE_ROOM_INFO_REQ(100007),
    /**
     * <code>GAME_CMD_UPDATE_ROOM_INFO_RESP = 100008;</code>
     */
    GAME_CMD_UPDATE_ROOM_INFO_RESP(100008),
    /**
     * <pre>
     *以下是srv向娃娃机的协议
     *初始化娃娃的天车参数及中奖几率
     * </pre>
     *
     * <code>DOLL_MACHINE_INIT_REQ = 110001;</code>
     */
    DOLL_MACHINE_INIT_REQ(110001),
    /**
     * <code>DOLL_MACHINE_INIT_RESP = 110002;</code>
     */
    DOLL_MACHINE_INIT_RESP(110002),
    /**
     * <pre>
     *srv告知娃娃机开始游戏的用户
     * </pre>
     *
     * <code>GAME_CMD_SRV_TAKE_WAWA_REQ = 110003;</code>
     */
    GAME_CMD_SRV_TAKE_WAWA_REQ(110003),
    /**
     * <code>GAME_CMD_SRV_TAKE_WAWA_RESP = 110004;</code>
     */
    GAME_CMD_SRV_TAKE_WAWA_RESP(110004),
    /**
     * <code>GAME_CMD_SRV_TAKE_SRV_RESP = 110005;</code>
     */
    GAME_CMD_SRV_TAKE_SRV_RESP(110005),
    /**
     * <pre>
     *以下是用户操作的请求
     *用户登录到go-serv
     * </pre>
     *
     * <code>GAME_CMD_USER_LOGIN_REQ = 120001;</code>
     */
    GAME_CMD_USER_LOGIN_REQ(120001),
    /**
     * <code>GAME_CMD_USER_LOGIN_RESP = 120002;</code>
     */
    GAME_CMD_USER_LOGIN_RESP(120002),
    /**
     * <pre>
     *心跳协议
     * </pre>
     *
     * <code>GAME_CMD_USER_HB_REQ = 120003;</code>
     */
    GAME_CMD_USER_HB_REQ(120003),
    /**
     * <code>GAME_CMD_USER_HB_RESP = 120004;</code>
     */
    GAME_CMD_USER_HB_RESP(120004),
    /**
     * <pre>
     *用户进入房间，获取房间详情信息
     * </pre>
     *
     * <code>GAME_CMD_USER_ENTER_ROOM_REQ = 120007;</code>
     */
    GAME_CMD_USER_ENTER_ROOM_REQ(120007),
    /**
     * <code>GAME_CMD_USER_ENTER_ROOM_RESP = 120008;</code>
     */
    GAME_CMD_USER_ENTER_ROOM_RESP(120008),
    /**
     * <pre>
     *用户预约上机
     * </pre>
     *
     * <code>GAME_CMD_USER_APPLY_REQ = 120017;</code>
     */
    GAME_CMD_USER_APPLY_REQ(120017),
    /**
     * <code>GAME_CMD_USER_APPLY_RESP = 120018;</code>
     */
    GAME_CMD_USER_APPLY_RESP(120018),
    /**
     * <pre>
     *通知用户上机(from srv)
     * </pre>
     *
     * <code>GAME_CMD_NOTIFY_USER_PLAY_REQ = 120019;</code>
     */
    GAME_CMD_NOTIFY_USER_PLAY_REQ(120019),
    /**
     * <pre>
     *通知上机的回应(from cli)
     * </pre>
     *
     * <code>GAME_CMD_NOTIFY_USER_PLAY_RESP = 120020;</code>
     */
    GAME_CMD_NOTIFY_USER_PLAY_RESP(120020),
    /**
     * <pre>
     *确认用户上机(from srv)
     * </pre>
     *
     * <code>GAME_CMD_CONFIRM_USER_PLAY_RESP = 120021;</code>
     */
    GAME_CMD_CONFIRM_USER_PLAY_RESP(120021),
    /**
     * <pre>
     *围观者离开房间
     * </pre>
     *
     * <code>GAME_CMD_VISITOR_LEAVE_REQ = 120022;</code>
     */
    GAME_CMD_VISITOR_LEAVE_REQ(120022),
    /**
     * <code>GAME_CMD_VISITOR_LEAVE_RESP = 120023;</code>
     */
    GAME_CMD_VISITOR_LEAVE_RESP(120023),
    /**
     * <pre>
     *srv通知cli 房间信息更新
     * </pre>
     *
     * <code>GAME_CMD_NOTI_ROOM_UPDATE_REQ = 120024;</code>
     */
    GAME_CMD_NOTI_ROOM_UPDATE_REQ(120024),
    /**
     * <code>GAME_CMD_NOTI_ROOM_UPDATE_RESP = 120025;</code>
     */
    GAME_CMD_NOTI_ROOM_UPDATE_RESP(120025),
    /**
     * <pre>
     *用户取消预约
     * </pre>
     *
     * <code>GAME_CMD_CANCEL_APPLY_REQ = 120026;</code>
     */
    GAME_CMD_CANCEL_APPLY_REQ(120026),
    /**
     * <code>GAME_CMD_CANCEL_APPLY_RESP = 120027;</code>
     */
    GAME_CMD_CANCEL_APPLY_RESP(120027),
    /**
     * <pre>
     *srv告知cli 需要登录
     * </pre>
     *
     * <code>GAME_CMD_NOT_LOGIN_RESP = 120028;</code>
     */
    GAME_CMD_NOT_LOGIN_RESP(120028),
    /**
     * <pre>
     *告知用户游戏结果
     * </pre>
     *
     * <code>GAME_CMD_NOTI_GAME_RESULT_RESP = 120029;</code>
     */
    GAME_CMD_NOTI_GAME_RESULT_RESP(120029),
    /**
     * <pre>
     *首页广播信息
     * </pre>
     *
     * <code>GAME_CMD_BROADCAST_RESP = 120030;</code>
     */
    GAME_CMD_BROADCAST_RESP(120030),
    /**
     * <code>GAME_CMD_CTRL_MSG_REQ = 150001;</code>
     */
    GAME_CMD_CTRL_MSG_REQ(150001),
    /**
     * <code>GAME_CMD_CTRL_MSG_RESP = 150002;</code>
     */
    GAME_CMD_CTRL_MSG_RESP(150002),
    /**
     * <code>GAME_CMD_CTRL_END_REQ = 150003;</code>
     */
    GAME_CMD_CTRL_END_REQ(150003),
    /**
     * <pre>
     *最大允许命令字
     * </pre>
     *
     * <code>GAME_CMD_MAX = 999999;</code>
     */
    GAME_CMD_MAX(999999),
    /**
     * <pre>
     *以下已废弃
     *列出娃娃机列表
     * </pre>
     *
     * <code>GAME_CMD_USER_ROOM_LIST_REQ = 120005;</code>
     */
    GAME_CMD_USER_ROOM_LIST_REQ(120005),
    /**
     * <code>GAME_CMD_USER_ROOM_LIST_RESP = 120006;</code>
     */
    GAME_CMD_USER_ROOM_LIST_RESP(120006),
    /**
     * <pre>
     *开始游戏
     * </pre>
     *
     * <code>GAME_CMD_USER_PLAY_REQ = 120009;</code>
     */
    GAME_CMD_USER_PLAY_REQ(120009),
    /**
     * <code>GAME_CMD_USER_PLAY_RESP = 120010;</code>
     */
    GAME_CMD_USER_PLAY_RESP(120010),
    /**
     * <pre>
     *退出游戏
     * </pre>
     *
     * <code>GAME_CMD_USER_QUIT_PLAY_REQ = 120011;</code>
     */
    GAME_CMD_USER_QUIT_PLAY_REQ(120011),
    /**
     * <code>GAME_CMD_USER_QUIT_PLAY_RESP = 120012;</code>
     */
    GAME_CMD_USER_QUIT_PLAY_RESP(120012),
    /**
     * <pre>
     *列出"娃娃机群"列表
     * </pre>
     *
     * <code>GAME_CMD_ROOM_GROUP_LIST_REQ = 120013;</code>
     */
    GAME_CMD_ROOM_GROUP_LIST_REQ(120013),
    /**
     * <code>GAME_CMD_ROOM_GROUP_LIST_RESP = 120014;</code>
     */
    GAME_CMD_ROOM_GROUP_LIST_RESP(120014),
    /**
     * <pre>
     *按指定娃娃，列出娃娃机列表
     * </pre>
     *
     * <code>GAME_CMD_ROOM_LIST_BY_DOLL_REQ = 120015;</code>
     */
    GAME_CMD_ROOM_LIST_BY_DOLL_REQ(120015),
    /**
     * <code>GAME_CMD_ROOM_LIST_BY_DOLL_RESP = 120016;</code>
     */
    GAME_CMD_ROOM_LIST_BY_DOLL_RESP(120016),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GAME_CMD_INIT = 0;</code>
     */
    public static final int GAME_CMD_INIT_VALUE = 0;
    /**
     * <pre>
     *以下是娃娃机自动向srv上报的请求
     *娃娃机初始化登录命令字,娃娃机向srv注册自己
     * </pre>
     *
     * <code>GAME_CMD_WAWA_REG_REQ = 100001;</code>
     */
    public static final int GAME_CMD_WAWA_REG_REQ_VALUE = 100001;
    /**
     * <code>GAME_CMD_WAWA_REG_RESP = 100002;</code>
     */
    public static final int GAME_CMD_WAWA_REG_RESP_VALUE = 100002;
    /**
     * <pre>
     *娃娃机抓取结果
     * </pre>
     *
     * <code>GAME_CMD_WAWA_NOTIFY_REQ = 100003;</code>
     */
    public static final int GAME_CMD_WAWA_NOTIFY_REQ_VALUE = 100003;
    /**
     * <code>GAME_CMD_WAWA_NOTIFY_RESP = 100004;</code>
     */
    public static final int GAME_CMD_WAWA_NOTIFY_RESP_VALUE = 100004;
    /**
     * <pre>
     *娃娃机心跳协议
     * </pre>
     *
     * <code>GAME_CMD_WAWA_HB_REQ = 100005;</code>
     */
    public static final int GAME_CMD_WAWA_HB_REQ_VALUE = 100005;
    /**
     * <code>GAME_CMD_WAWA_HB_RESP = 100006;</code>
     */
    public static final int GAME_CMD_WAWA_HB_RESP_VALUE = 100006;
    /**
     * <pre>
     *娃娃机向srv更新信息(cover)
     * </pre>
     *
     * <code>GAME_CMD_UPDATE_ROOM_INFO_REQ = 100007;</code>
     */
    public static final int GAME_CMD_UPDATE_ROOM_INFO_REQ_VALUE = 100007;
    /**
     * <code>GAME_CMD_UPDATE_ROOM_INFO_RESP = 100008;</code>
     */
    public static final int GAME_CMD_UPDATE_ROOM_INFO_RESP_VALUE = 100008;
    /**
     * <pre>
     *以下是srv向娃娃机的协议
     *初始化娃娃的天车参数及中奖几率
     * </pre>
     *
     * <code>DOLL_MACHINE_INIT_REQ = 110001;</code>
     */
    public static final int DOLL_MACHINE_INIT_REQ_VALUE = 110001;
    /**
     * <code>DOLL_MACHINE_INIT_RESP = 110002;</code>
     */
    public static final int DOLL_MACHINE_INIT_RESP_VALUE = 110002;
    /**
     * <pre>
     *srv告知娃娃机开始游戏的用户
     * </pre>
     *
     * <code>GAME_CMD_SRV_TAKE_WAWA_REQ = 110003;</code>
     */
    public static final int GAME_CMD_SRV_TAKE_WAWA_REQ_VALUE = 110003;
    /**
     * <code>GAME_CMD_SRV_TAKE_WAWA_RESP = 110004;</code>
     */
    public static final int GAME_CMD_SRV_TAKE_WAWA_RESP_VALUE = 110004;
    /**
     * <code>GAME_CMD_SRV_TAKE_SRV_RESP = 110005;</code>
     */
    public static final int GAME_CMD_SRV_TAKE_SRV_RESP_VALUE = 110005;
    /**
     * <pre>
     *以下是用户操作的请求
     *用户登录到go-serv
     * </pre>
     *
     * <code>GAME_CMD_USER_LOGIN_REQ = 120001;</code>
     */
    public static final int GAME_CMD_USER_LOGIN_REQ_VALUE = 120001;
    /**
     * <code>GAME_CMD_USER_LOGIN_RESP = 120002;</code>
     */
    public static final int GAME_CMD_USER_LOGIN_RESP_VALUE = 120002;
    /**
     * <pre>
     *心跳协议
     * </pre>
     *
     * <code>GAME_CMD_USER_HB_REQ = 120003;</code>
     */
    public static final int GAME_CMD_USER_HB_REQ_VALUE = 120003;
    /**
     * <code>GAME_CMD_USER_HB_RESP = 120004;</code>
     */
    public static final int GAME_CMD_USER_HB_RESP_VALUE = 120004;
    /**
     * <pre>
     *用户进入房间，获取房间详情信息
     * </pre>
     *
     * <code>GAME_CMD_USER_ENTER_ROOM_REQ = 120007;</code>
     */
    public static final int GAME_CMD_USER_ENTER_ROOM_REQ_VALUE = 120007;
    /**
     * <code>GAME_CMD_USER_ENTER_ROOM_RESP = 120008;</code>
     */
    public static final int GAME_CMD_USER_ENTER_ROOM_RESP_VALUE = 120008;
    /**
     * <pre>
     *用户预约上机
     * </pre>
     *
     * <code>GAME_CMD_USER_APPLY_REQ = 120017;</code>
     */
    public static final int GAME_CMD_USER_APPLY_REQ_VALUE = 120017;
    /**
     * <code>GAME_CMD_USER_APPLY_RESP = 120018;</code>
     */
    public static final int GAME_CMD_USER_APPLY_RESP_VALUE = 120018;
    /**
     * <pre>
     *通知用户上机(from srv)
     * </pre>
     *
     * <code>GAME_CMD_NOTIFY_USER_PLAY_REQ = 120019;</code>
     */
    public static final int GAME_CMD_NOTIFY_USER_PLAY_REQ_VALUE = 120019;
    /**
     * <pre>
     *通知上机的回应(from cli)
     * </pre>
     *
     * <code>GAME_CMD_NOTIFY_USER_PLAY_RESP = 120020;</code>
     */
    public static final int GAME_CMD_NOTIFY_USER_PLAY_RESP_VALUE = 120020;
    /**
     * <pre>
     *确认用户上机(from srv)
     * </pre>
     *
     * <code>GAME_CMD_CONFIRM_USER_PLAY_RESP = 120021;</code>
     */
    public static final int GAME_CMD_CONFIRM_USER_PLAY_RESP_VALUE = 120021;
    /**
     * <pre>
     *围观者离开房间
     * </pre>
     *
     * <code>GAME_CMD_VISITOR_LEAVE_REQ = 120022;</code>
     */
    public static final int GAME_CMD_VISITOR_LEAVE_REQ_VALUE = 120022;
    /**
     * <code>GAME_CMD_VISITOR_LEAVE_RESP = 120023;</code>
     */
    public static final int GAME_CMD_VISITOR_LEAVE_RESP_VALUE = 120023;
    /**
     * <pre>
     *srv通知cli 房间信息更新
     * </pre>
     *
     * <code>GAME_CMD_NOTI_ROOM_UPDATE_REQ = 120024;</code>
     */
    public static final int GAME_CMD_NOTI_ROOM_UPDATE_REQ_VALUE = 120024;
    /**
     * <code>GAME_CMD_NOTI_ROOM_UPDATE_RESP = 120025;</code>
     */
    public static final int GAME_CMD_NOTI_ROOM_UPDATE_RESP_VALUE = 120025;
    /**
     * <pre>
     *用户取消预约
     * </pre>
     *
     * <code>GAME_CMD_CANCEL_APPLY_REQ = 120026;</code>
     */
    public static final int GAME_CMD_CANCEL_APPLY_REQ_VALUE = 120026;
    /**
     * <code>GAME_CMD_CANCEL_APPLY_RESP = 120027;</code>
     */
    public static final int GAME_CMD_CANCEL_APPLY_RESP_VALUE = 120027;
    /**
     * <pre>
     *srv告知cli 需要登录
     * </pre>
     *
     * <code>GAME_CMD_NOT_LOGIN_RESP = 120028;</code>
     */
    public static final int GAME_CMD_NOT_LOGIN_RESP_VALUE = 120028;
    /**
     * <pre>
     *告知用户游戏结果
     * </pre>
     *
     * <code>GAME_CMD_NOTI_GAME_RESULT_RESP = 120029;</code>
     */
    public static final int GAME_CMD_NOTI_GAME_RESULT_RESP_VALUE = 120029;
    /**
     * <pre>
     *首页广播信息
     * </pre>
     *
     * <code>GAME_CMD_BROADCAST_RESP = 120030;</code>
     */
    public static final int GAME_CMD_BROADCAST_RESP_VALUE = 120030;
    /**
     * <code>GAME_CMD_CTRL_MSG_REQ = 150001;</code>
     */
    public static final int GAME_CMD_CTRL_MSG_REQ_VALUE = 150001;
    /**
     * <code>GAME_CMD_CTRL_MSG_RESP = 150002;</code>
     */
    public static final int GAME_CMD_CTRL_MSG_RESP_VALUE = 150002;
    /**
     * <code>GAME_CMD_CTRL_END_REQ = 150003;</code>
     */
    public static final int GAME_CMD_CTRL_END_REQ_VALUE = 150003;
    /**
     * <pre>
     *最大允许命令字
     * </pre>
     *
     * <code>GAME_CMD_MAX = 999999;</code>
     */
    public static final int GAME_CMD_MAX_VALUE = 999999;
    /**
     * <pre>
     *以下已废弃
     *列出娃娃机列表
     * </pre>
     *
     * <code>GAME_CMD_USER_ROOM_LIST_REQ = 120005;</code>
     */
    public static final int GAME_CMD_USER_ROOM_LIST_REQ_VALUE = 120005;
    /**
     * <code>GAME_CMD_USER_ROOM_LIST_RESP = 120006;</code>
     */
    public static final int GAME_CMD_USER_ROOM_LIST_RESP_VALUE = 120006;
    /**
     * <pre>
     *开始游戏
     * </pre>
     *
     * <code>GAME_CMD_USER_PLAY_REQ = 120009;</code>
     */
    public static final int GAME_CMD_USER_PLAY_REQ_VALUE = 120009;
    /**
     * <code>GAME_CMD_USER_PLAY_RESP = 120010;</code>
     */
    public static final int GAME_CMD_USER_PLAY_RESP_VALUE = 120010;
    /**
     * <pre>
     *退出游戏
     * </pre>
     *
     * <code>GAME_CMD_USER_QUIT_PLAY_REQ = 120011;</code>
     */
    public static final int GAME_CMD_USER_QUIT_PLAY_REQ_VALUE = 120011;
    /**
     * <code>GAME_CMD_USER_QUIT_PLAY_RESP = 120012;</code>
     */
    public static final int GAME_CMD_USER_QUIT_PLAY_RESP_VALUE = 120012;
    /**
     * <pre>
     *列出"娃娃机群"列表
     * </pre>
     *
     * <code>GAME_CMD_ROOM_GROUP_LIST_REQ = 120013;</code>
     */
    public static final int GAME_CMD_ROOM_GROUP_LIST_REQ_VALUE = 120013;
    /**
     * <code>GAME_CMD_ROOM_GROUP_LIST_RESP = 120014;</code>
     */
    public static final int GAME_CMD_ROOM_GROUP_LIST_RESP_VALUE = 120014;
    /**
     * <pre>
     *按指定娃娃，列出娃娃机列表
     * </pre>
     *
     * <code>GAME_CMD_ROOM_LIST_BY_DOLL_REQ = 120015;</code>
     */
    public static final int GAME_CMD_ROOM_LIST_BY_DOLL_REQ_VALUE = 120015;
    /**
     * <code>GAME_CMD_ROOM_LIST_BY_DOLL_RESP = 120016;</code>
     */
    public static final int GAME_CMD_ROOM_LIST_BY_DOLL_RESP_VALUE = 120016;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GAME_CMD valueOf(int value) {
      return forNumber(value);
    }

    public static GAME_CMD forNumber(int value) {
      switch (value) {
        case 0: return GAME_CMD_INIT;
        case 100001: return GAME_CMD_WAWA_REG_REQ;
        case 100002: return GAME_CMD_WAWA_REG_RESP;
        case 100003: return GAME_CMD_WAWA_NOTIFY_REQ;
        case 100004: return GAME_CMD_WAWA_NOTIFY_RESP;
        case 100005: return GAME_CMD_WAWA_HB_REQ;
        case 100006: return GAME_CMD_WAWA_HB_RESP;
        case 100007: return GAME_CMD_UPDATE_ROOM_INFO_REQ;
        case 100008: return GAME_CMD_UPDATE_ROOM_INFO_RESP;
        case 110001: return DOLL_MACHINE_INIT_REQ;
        case 110002: return DOLL_MACHINE_INIT_RESP;
        case 110003: return GAME_CMD_SRV_TAKE_WAWA_REQ;
        case 110004: return GAME_CMD_SRV_TAKE_WAWA_RESP;
        case 110005: return GAME_CMD_SRV_TAKE_SRV_RESP;
        case 120001: return GAME_CMD_USER_LOGIN_REQ;
        case 120002: return GAME_CMD_USER_LOGIN_RESP;
        case 120003: return GAME_CMD_USER_HB_REQ;
        case 120004: return GAME_CMD_USER_HB_RESP;
        case 120007: return GAME_CMD_USER_ENTER_ROOM_REQ;
        case 120008: return GAME_CMD_USER_ENTER_ROOM_RESP;
        case 120017: return GAME_CMD_USER_APPLY_REQ;
        case 120018: return GAME_CMD_USER_APPLY_RESP;
        case 120019: return GAME_CMD_NOTIFY_USER_PLAY_REQ;
        case 120020: return GAME_CMD_NOTIFY_USER_PLAY_RESP;
        case 120021: return GAME_CMD_CONFIRM_USER_PLAY_RESP;
        case 120022: return GAME_CMD_VISITOR_LEAVE_REQ;
        case 120023: return GAME_CMD_VISITOR_LEAVE_RESP;
        case 120024: return GAME_CMD_NOTI_ROOM_UPDATE_REQ;
        case 120025: return GAME_CMD_NOTI_ROOM_UPDATE_RESP;
        case 120026: return GAME_CMD_CANCEL_APPLY_REQ;
        case 120027: return GAME_CMD_CANCEL_APPLY_RESP;
        case 120028: return GAME_CMD_NOT_LOGIN_RESP;
        case 120029: return GAME_CMD_NOTI_GAME_RESULT_RESP;
        case 120030: return GAME_CMD_BROADCAST_RESP;
        case 150001: return GAME_CMD_CTRL_MSG_REQ;
        case 150002: return GAME_CMD_CTRL_MSG_RESP;
        case 150003: return GAME_CMD_CTRL_END_REQ;
        case 999999: return GAME_CMD_MAX;
        case 120005: return GAME_CMD_USER_ROOM_LIST_REQ;
        case 120006: return GAME_CMD_USER_ROOM_LIST_RESP;
        case 120009: return GAME_CMD_USER_PLAY_REQ;
        case 120010: return GAME_CMD_USER_PLAY_RESP;
        case 120011: return GAME_CMD_USER_QUIT_PLAY_REQ;
        case 120012: return GAME_CMD_USER_QUIT_PLAY_RESP;
        case 120013: return GAME_CMD_ROOM_GROUP_LIST_REQ;
        case 120014: return GAME_CMD_ROOM_GROUP_LIST_RESP;
        case 120015: return GAME_CMD_ROOM_LIST_BY_DOLL_REQ;
        case 120016: return GAME_CMD_ROOM_LIST_BY_DOLL_RESP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GAME_CMD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GAME_CMD> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GAME_CMD>() {
            public GAME_CMD findValueByNumber(int number) {
              return GAME_CMD.forNumber(number);
            }
          };

    private final int value;

    private GAME_CMD(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:boomegg.cn.wawa.proto.GAME_CMD)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
